server:
  port: 9001

launchdarkly:
  sdkKey: ${LAUNCHDARKLY_SDK_KEY}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  server:
    port: 10100
  health:
    liveness-indicator:
      enabled: true
    startup-indicator:
      enabled: true
    readiness-indicator:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
    info:
      enabled: true